treedata={
	"accessurl": "top",
	"createuser": "wangyijian",
	"enddate": "2012/09/06",
	"isaccessable": "1",
	"haschildren": true,
	"projectid": 1,
	"begindate": "2012/09/06",
	"parentid": 0,
	"userid": "admin",
	"template": "todo",
	"projectname": "top",
	"ChildNodes": [{
		"accessurl": "project8",
		"createuser": "wangyijian",
		"enddate": "2012/09/29",
		"isaccessable": "1",
		"haschildren": true,
		"projectid": 43,
		"begindate": "2012/09/12",
		"parentid": 1,
		"userid": "admin",
		"template": "todo",
		"projectname": "pj8",
		"ChildNodes": [{
			"accessurl": "project9",
			"createuser": "wangyijian",
			"enddate": "2012/09/20",
			"isaccessable": "0",
			"haschildren": true,
			"projectid": 44,
			"begindate": "2012/09/13",
			"parentid": 43,
			"userid": "admin",
			"template": "todo",
			"projectname": "pj9",
			"ChildNodes": [{
				"accessurl": "project10",
				"createuser": "wangyijian",
				"enddate": "2012/09/29",
				"isaccessable": "0",
				"haschildren": false,
				"projectid": 45,
				"begindate": "2012/09/19",
				"parentid": 44,
				"userid": "admin",
				"template": "todo",
				"projectname": "pj10",
				"ChildNodes": null,
				"createdate": "2012/09/07"
			}],
			"createdate": "2012/09/07"
		},
		{
			"accessurl": "project11",
			"createuser": "wangyijian",
			"enddate": "2012/09/02",
			"isaccessable": "0",
			"haschildren": false,
			"projectid": 46,
			"begindate": "2012/08/01",
			"parentid": 43,
			"userid": "admin",
			"template": "todo",
			"projectname": "pj11",
			"ChildNodes": null,
			"createdate": "2012/09/08"
		}],
		"createdate": "2012/09/07"
	}],
	"createdate": "2012/09/06"
};